
-- Creacion de tabla temporal

CREATE TABLE IF NOT EXISTS Temporal (
	NOMBRE_CLIENTE VARCHAR(100),
	CORREO_CLIENTE VARCHAR(100),
	CLIENTE_ACTIVO VARCHAR(25),
	FECHA_CREACION VARCHAR(100),
	TIENDA_PREFERIDA VARCHAR(100),
	DIRECCION_CLIENTE VARCHAR(2000),
	CODIGO_POSTAL_CLIENTE VARCHAR(100),
	CIUDAD_CLIENTE VARCHAR(100),
	PAIS_CLIENTE VARCHAR(100),
	FECHA_RENTA VARCHAR(100),
	FECHA_RETORNO VARCHAR(100),
	MONTO_A_PAGAR VARCHAR(50),
	FECHA_PAGO VARCHAR(60),
	NOMBRE_EMPLEADO VARCHAR(100),
	CORREO_EMPLEADO VARCHAR(100),
	EMPLEADO_ACTIVO VARCHAR(50),
	TIENDA_EMPLEADO VARCHAR(100),
	USUARIO_EMPLEADO VARCHAR(100),
	CONTRASENIA_EMPLEADO VARCHAR(200),
	DIRECCION_EMPLEADO VARCHAR(250),
	CODIGO_POSTAL_EMPLEADO VARCHAR(50),
	CIUDAD_EMPLEADO VARCHAR(100),
	PAIS_EMPLEADO VARCHAR(100),
	NOMBRE_TIENDA VARCHAR(100),
	ENCARGADO_TIENDA VARCHAR(100),
	DIRECCION_TIENDA VARCHAR(200),
	CODIGO_POSTAL_TIENDA VARCHAR(50),
	CIUDAD_TIENDA VARCHAR(100),
	PAIS_TIENDA VARCHAR(100),
	TIENDA_PELICULA VARCHAR(100),
	NOMBRE_PELICULA VARCHAR(200),
	DESCRIPCION_PELICULA VARCHAR(300),
	ANIO_LANZAMIENTO VARCHAR(50),
	DIAS_RENTA VARCHAR(50),
	COSTO_RENTA VARCHAR(50),
	DURACION VARCHAR(50),
	COSTO_POR_ANIO VARCHAR(50),
	CLASIFICACION VARCHAR(100),
	LENGUAJE_PELICULA VARCHAR(100),
	CATEGORIA_PELICULA VARCHAR(100),
	ACTOR_PELICULA VARCHAR(100)
);

-- drop table Temporal;

-- Carga masiva, delimitar con ';'
-- Ejecutar desde SQL Shell

-- No se si funciona :(
-- copy Temporal (NOMBRE_CLIENTE,CORREO_CLIENTE,CLIENTE_ACTIVO,FECHA_CREACION,TIENDA_PREFERIDA,
-- 			   DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,CIUDAD_CLIENTE,PAIS_CLIENTE,FECHA_RENTA,
-- 			   FECHA_RETORNO,MONTO_A_PAGAR,FECHA_PAGO,NOMBRE_EMPLEADO,CORREO_EMPLEADO,
-- 			   EMPLEADO_ACTIVO,TIENDA_EMPLEADO,USUARIO_EMPLEADO,CONTRASENIA_EMPLEADO,
-- 			   DIRECCION_EMPLEADO,CODIGO_POSTAL_EMPLEADO,CIUDAD_EMPLEADO,PAIS_EMPLEADO,
-- 			   NOMBRE_TIENDA,ENCARGADO_TIENDA,DIRECCION_TIENDA,CODIGO_POSTAL_TIENDA,
-- 			   CIUDAD_TIENDA,PAIS_TIENDA,TIENDA_PELICULA,NOMBRE_PELICULA,DESCRIPCION_PELICULA,
-- 			   ANIO_LANZAMIENTO,DIAS_RENTA,COSTO_RENTA,DURACION,COSTO_POR_ANIO,CLASIFICACION,
-- 			   LENGUAJE_PELICULA,CATEGORIA_PELICULA,ACTOR_PELICULA)
-- 	from 'C:/Users/Alexander/Documents/Bases1/Practica3/BlockbusterData1.csv' using delimiters ';'  with csv;

-- Ejecutar desde SQL Shell
-- Este funciona!
COPY Temporal FROM 'C:/Users/Alexander/Documents/Bases1/Practica3/BlockbusterData.csv' DELIMITER ';' CSV HEADER;
COPY Temporal FROM 'C:/Users/Alexander/Documents/Bases1/Practica3/BlockbusterData1.csv' DELIMITER ';' CSV HEADER;

SELECT COUNT(*) FROM temporal;
